#!/usr/bin/env zsh
#
# magic keyword
# * default
#

for conf in /etc/zsh/zshrc $HOME/.zshrc; do
    [ -f "$conf" ] && source $conf
done

if [ $# -le 0 ]; then
    exec tmux new -c $HOME -As default
else
    exec tmux attach -t "$@"
fi
