#!/usr/bin/env zsh
#
# magic keyword
# * default
#

for conf in /etc/zsh/zshrc $HOME/.zshrc; do
    [ -f "$conf" ] && source $conf
done

session="$1"
if [ -n "$session" ]; then
    exec tmux attach -t "$session"
fi

session=default

if tmux has -t "$session" &>/dev/null; then
    exec tmux attach -t "$session"
else
    exec tmux new -s "$session"
fi

